# Generated by Django 2.2.28 on 2023-02-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_category_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
